# Generated by Django 3.2 on 2022-05-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descriptions du pack'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix'),
        ),
        migrations.AlterField(
            model_name='surface',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix'),
        ),
    ]
