# Generated by Django 3.2 on 2022-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20220508_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='porte',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de fenetre'),
        ),
    ]
