# Generated by Django 3.2 on 2022-05-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_surface_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surface',
            name='price',
        ),
        migrations.AddField(
            model_name='surface',
            name='surface_moyenne',
            field=models.IntegerField(blank=True, null=True, verbose_name='surface moyenne'),
        ),
    ]
