# Generated by Django 3.2 on 2022-05-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20220508_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bien',
            options={'verbose_name': 'bien', 'verbose_name_plural': 'biens'},
        ),
        migrations.RemoveField(
            model_name='surface',
            name='surface_moyenne',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='unite',
        ),
        migrations.AddField(
            model_name='surface',
            name='price',
            field=models.IntegerField(default=0, verbose_name='prix'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='price',
            field=models.IntegerField(default=0, verbose_name='prix'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='price',
            field=models.IntegerField(default=0, verbose_name='prix'),
        ),
    ]
