# Generated by Django 3.2 on 2022-05-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20220508_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='birth_place',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
