# Generated by Django 3.2 on 2022-05-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20220510_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='experience'),
        ),
    ]
