# Generated by Django 3.2 on 2022-05-15 08:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_alter_hiring_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'entreprise")),
                ('image_high', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='img_1')),
                ('image_low', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='img_1')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Titre')),
                ('about_high', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text a propos')),
                ('about_low', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Page dossier taksit')),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('logo', models.ImageField(upload_to='images/logos', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='images/logos', verbose_name='Favicon')),
                ('logo_negatif', models.ImageField(blank=True, null=True, upload_to='images/slides', verbose_name='Logo négatif')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Titre')),
                ('adress', models.CharField(blank=True, max_length=50, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name="email de l'entreprise")),
                ('email2', models.EmailField(blank=True, max_length=50, verbose_name="2eme email de l'entreprise")),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name="numéro de téléphone de l'entreprise")),
                ('phone2', models.CharField(blank=True, max_length=50, null=True, verbose_name="2eme numéro de téléphone de l'entreprise")),
                ('phone3', models.CharField(blank=True, max_length=50, null=True, verbose_name="3eme numéro de téléphone de l'entreprise")),
                ('about', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text a propos')),
                ('folder_page', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Page dossier taksit')),
                ('mini_about', models.TextField(blank=True, null=True, verbose_name="Petit texte a propos de l'entreprise ( bas de page)")),
                ('about_photo', models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Photo A propos 440 X 275 px')),
                ('bottom_banner', models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Banner bas de page 1920 px largeur')),
                ('partner_logo', models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Logo partenaire')),
                ('partner_logo2', models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Logo partenaire 2')),
                ('facebook', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien page Facebook')),
                ('insta', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien page Instagram')),
                ('linkedin', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien page LinkedIn')),
                ('twitter', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien Compte Twitter')),
                ('youtube', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien Chaine Youtube')),
            ],
            options={
                'verbose_name': ' Infomation',
                'verbose_name_plural': ' Infomations',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='slides/', verbose_name='Slide haut de page')),
                ('url', models.URLField(blank=True, max_length=250, null=True, verbose_name='Lien')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': " Slides haut page d'accueil",
                'verbose_name_plural': " Slides haut page d'accueil",
            },
        ),
    ]
