# Generated by Django 3.2 on 2022-05-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_about_business_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'slide', 'verbose_name_plural': 'slides'},
        ),
        migrations.RemoveField(
            model_name='slide',
            name='url',
        ),
    ]
