# Generated by Django 3.2 on 2022-05-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20220515_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image du service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='service'),
        ),
    ]
