# Generated by Django 3.2 on 2022-05-15 12:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20220515_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='sssss'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='about_low',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Page a propos 2'),
        ),
        migrations.AlterField(
            model_name='service',
            name='about_high',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='about_low',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Page service '),
        ),
    ]
