# Generated by Django 3.2 on 2022-05-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_auto_20220515_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='folder_page',
            new_name='about_2',
        ),
        migrations.RemoveField(
            model_name='business',
            name='bottom_banner',
        ),
        migrations.RemoveField(
            model_name='business',
            name='partner_logo',
        ),
        migrations.RemoveField(
            model_name='business',
            name='partner_logo2',
        ),
        migrations.RemoveField(
            model_name='business',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='business',
            name='youtube',
        ),
        migrations.AddField(
            model_name='business',
            name='about_photo2',
            field=models.ImageField(blank=True, null=True, upload_to='images/slides', verbose_name="Photo a propos Page d'accueil "),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_high',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_low',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_2'),
        ),
        migrations.AlterField(
            model_name='business',
            name='about_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/slides', verbose_name='Photo a propos '),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_high',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_detail_1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_low',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image_detail_2'),
        ),
    ]
