# Generated by Django 3.2 on 2022-05-16 08:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20220515_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='name_ar',
            field=models.CharField(default='dfbdfbdf', max_length=25, verbose_name='type de bien en arabe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='name_ar',
            field=models.CharField(default='hg,h,n,,tzze', max_length=100, verbose_name="Nom de l'entreprise en arabe"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formule',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Descriptions du pack en arabe'),
        ),
        migrations.AddField(
            model_name='formule',
            name='formule_ar',
            field=models.CharField(default='dvsd', max_length=150, verbose_name='Pack nettoyage en arabe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='about_high_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text service'),
        ),
        migrations.AddField(
            model_name='service',
            name='about_high_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text service'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='service'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='service'),
        ),
    ]
