# Generated by Django 3.2 on 2022-05-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_auto_20220516_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='formule_ar',
        ),
    ]
