# Generated by Django 3.2 on 2022-05-16 09:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_auto_20220516_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='about_low_ar_dz',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Page service '),
        ),
        migrations.AddField(
            model_name='service',
            name='about_low_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Page service '),
        ),
    ]
