# Generated by Django 3.2 on 2022-05-16 09:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_auto_20220516_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_high_ar_dz',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text a propos'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_high_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text a propos'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_low_ar_dz',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Page a propos 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_low_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Page a propos 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ar_dz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='about',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ar_dz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titre'),
        ),
    ]
