# Generated by Django 3.2 on 2022-05-16 10:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_auto_20220516_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='about_2_ar_dz',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name="Page d'accueil"),
        ),
        migrations.AddField(
            model_name='business',
            name='about_2_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name="Page d'accueil"),
        ),
        migrations.AddField(
            model_name='business',
            name='about_ar_dz',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text a propos'),
        ),
        migrations.AddField(
            model_name='business',
            name='about_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text a propos'),
        ),
        migrations.AddField(
            model_name='business',
            name='adress_ar_dz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='business',
            name='adress_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='business',
            name='mini_about_ar_dz',
            field=models.TextField(blank=True, null=True, verbose_name="Petit texte a propos de l'entreprise ( bas de page)"),
        ),
        migrations.AddField(
            model_name='business',
            name='mini_about_fr',
            field=models.TextField(blank=True, null=True, verbose_name="Petit texte a propos de l'entreprise ( bas de page)"),
        ),
        migrations.AddField(
            model_name='business',
            name='name_ar_dz',
            field=models.CharField(max_length=100, null=True, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='business',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='business',
            name='title_ar_dz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='business',
            name='title_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titre'),
        ),
    ]
