# Generated by Django 3.2 on 2022-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_auto_20220516_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='description_ar_dz',
            field=models.TextField(blank=True, null=True, verbose_name='Descriptions du pack'),
        ),
        migrations.AddField(
            model_name='formule',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Descriptions du pack'),
        ),
        migrations.AddField(
            model_name='formule',
            name='formule_ar_dz',
            field=models.CharField(max_length=150, null=True, verbose_name='Pack nettoyage'),
        ),
        migrations.AddField(
            model_name='formule',
            name='formule_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='Pack nettoyage'),
        ),
    ]
