# Generated by Django 3.2 on 2022-05-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_auto_20220516_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='name_ar_dz',
            field=models.CharField(max_length=25, null=True, verbose_name='type de bien'),
        ),
        migrations.AddField(
            model_name='bien',
            name='name_fr',
            field=models.CharField(max_length=25, null=True, verbose_name='type de bien'),
        ),
    ]
