# Generated by Django 3.2 on 2022-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_auto_20220516_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email3',
            field=models.EmailField(blank=True, max_length=50, verbose_name='email de receptions, contact, devis, recrutement'),
        ),
    ]
