# Generated by Django 3.2 on 2022-05-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_business_email3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_high_ar_dz',
            new_name='about_high_ar',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='about_low_ar_dz',
            new_name='about_low_ar',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name_ar_dz',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='title_ar_dz',
            new_name='title_ar',
        ),
        migrations.RenameField(
            model_name='bien',
            old_name='name_ar_dz',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='about_2_ar_dz',
            new_name='about_2_ar',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='about_ar_dz',
            new_name='about_ar',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='adress_ar_dz',
            new_name='adress_ar',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='mini_about_ar_dz',
            new_name='mini_about_ar',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='name_ar_dz',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='title_ar_dz',
            new_name='title_ar',
        ),
        migrations.RenameField(
            model_name='formule',
            old_name='description_ar_dz',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='formule',
            old_name='formule_ar_dz',
            new_name='formule_ar',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='about_high_ar_dz',
            new_name='about_high_ar',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='about_low_ar_dz',
            new_name='about_low_ar',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name_ar_dz',
            new_name='name_ar',
        ),
    ]
