# Generated by Django 3.2.12 on 2022-10-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_auto_20220530_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='adress',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='business',
            name='adress_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='business',
            name='adress_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
    ]
